# Generated by Django 3.1.4 on 2020-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('cod_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='C. Postal')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
